export const ENABLE_ORBIT_CONTROLS = "ENABLE_ORBIT_CONTROLS";
export const DISABLE_ORBIT_CONTROLS = "DISABLE_ORBIT_CONTROLS";
export const ENABLE_SKY = "ENABLE_SKY";
export const DISABLE_SKY = "DISABLE_SKY";
export const SET_BRUSH_OPACITY = "SET_BRUSH_OPACITY";
export const SET_BRUSH_SIZE = "SET_BRUSH_SIZE";
